# docker-compose.yml
version: '3'
services:

  prometheus:
    image : prom/prometheus
    volumes:
     - ./prometheus/:/etc/prometheus/
     - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
  snmp-exporter:
    image: prom/snmp-exporter
    ports:
      - '9116:9116'
  node-exporter:
    image: prom/node-exporter
    ports:
      - '9100:9100'
  grafana:
    image: grafana/grafana:3.0.0-beta7
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
volumes:
    prometheus_data: {}
    grafana_data: {}

