# docker-compose.yml
version: '3'
services:

  prometheus:
    image : prom/prometheus
    volumes:
     - ./prometheus/:/etc/prometheus/
     - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - '9090:9090'
    depends_on:
      - snmp-exporter
      - node-exporter

  snmp-exporter:
    image: prom/snmp-exporter
    volumes:
      - ./snmp_exporter/:/etc/snmp_exporter/
    expose:
      - 9116

  node-exporter:
    image: prom/node-exporter
    expose:
      - 9100
  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    expose:
      - 3000
    ports:
      - "3000:3000"
volumes:
    prometheus_data: {}
    grafana_data: {}

